export const EVENT_AUTH = {
  SAVE_TOKEN_REDIS: 'SAVE_TOKEN_REDIS',
  DEL_TOKEN_REDIS: 'DEL_TOKEN_REDIS',
  LOGOUT: 'LOGOUT',
  SEND_MAIL_OTP: 'SEND_MAIL_OTP',
  SEND_MAIL_OTP_CHANGE_PASS: 'SEND_MAIL_OTP_CHANGE_PASS'
};
