export const RoutingKey = {
  AUTH: {
    LOGIN: 'LOGIN',
    LOGIN_GUEST: 'LOGIN_GUEST',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    REFRESH_TOKEN: 'REFRESH_TOKEN',
    CHECK_TOKEN: 'CHECK_TOKEN'
  },
  MOBILE_BE: {
    REGISTER: 'ME_REGISTER',
    LOGIN: 'ME_LOGIN',
    REFRESHTOKEN: 'ME_REFRESH_TOKEN',
    LOGOUT: 'ME_LOGOUT',
    VERIFY_OTP: 'ME_VERIFY_OTP',
    CHECK_JWT_TOKEN: 'CHECK_JWT_TOKEN'
  }
};
